### ISSUE TITLE
Interpreters for DOS

### ISSUE THREAD

**Issue by niutech** [balintkissdev/awesome-dos#3]
There are many programming language interpreters for DOS, please add them:
- [PythonD - Python for DOS](http://www.caddit.net/pythond/)
- [Micropython for FreeDOS](https://github.com/pohmelie/micropython-freedos)
- [Lua for DOS](https://archive.org/details/lua5.3.5)
- [perldos - Perl for DOS](https://perldoc.perl.org/perldos)
- [DOjS - JavaScript for DOS](https://github.com/SuperIlu/DOjS)

**Comment by balintkissdev** [comment]
Thanks, will do.

**Comment by balintkissdev** [comment]
Done! :slightly_smiling_face:

**Comment by niutech** [comment]
Thank you!

**Comment by coolcoder613eb** [comment]
New! RustPython for DOS.
https://github.com/coolcoder613eb/RustPython
using [w2c2](https://github.com/turbolent/w2c2)
