### ISSUE TITLE
Programming Sound Cards CD

### ISSUE THREAD

**Issue by Sembiance** [balintkissdev/awesome-dos#6]
A new website called DiscMaster has a bunch of programming CDs, including one called: Programming Sound Cards
http://discmaster.textfiles.com/browse/63/Programming%20Sound%20Cards.iso

The directory names are not very descriptive, but looking in a couple of the folders I found lots of example source code for working with sound cards under DOS. May want to add a link to this resource.

Additionally I found another CD with very little searching: Programmers Heaven 1
They have a section for MS-DOS programming: http://discmaster.textfiles.com/view/4555/Programmer's%20Heaven%20(InfoMagic)(March%201997).BIN/www/about.htm

There is probably a ton of other DOS programming resources on that site.

**Comment by volkertb** [comment]
Not to completely hijack your thread, @Sembiance, but this seems related:

One specific piece of DOS sound card programming documentation and SDK I have been looking for is the `MS-DOS Developers Kit for the Windows Sound System`. I suspect it comes with two binary blobs for WSS-compatible sound cards. These binary files were distributed with the source code of the [DIGPAK sound drivers](https://github.com/jratcliff63367), but it would be nice to get clarity on the terms on which these blobs and the Developers Kit were released.

See [my post in this other GitHub thread](https://github.com/jratcliff63367/digpak/pull/6#issuecomment-975999393) for more background and info on this.

If anybody reading this happens to have a copy of this Developers Kit, which I haven't been able to find on-line so far, please let me know! Thanks. :slightly_smiling_face:

**Comment by balintkissdev** [comment]
Hey @Sembiance and @volkertb !

Thanks for the findings! I will take a look at them and include in the list. Sorry for not reacting, I still have to clean up my e-mail notifications to see updates to this repo.
